### ISSUE TITLE
callLine function

### ISSUE THREAD

**Issue by HGeertsma** [pwbrown/telos-client#1]
First of all, this library looks promising and works already very well!
But to be able to fully implement the library in our workflow i want to be able to place a call on a handset with a remote command, unfortunatly this function (and i guess also the takeLine function) aren't yet fully functional at the moment.
So my question is when can we expect an update of this library where those function will be ready and added to the repository?

**Comment by pwbrown** [comment]
Thanks @HGeertsma for the concerns.  I started writing this package to replace my outdated library "vx-client" during the summer as part of an effort to build replacement software for our radio studio.  Unfortunately I was tasked with starting several other projects and had to lay this aside for a while. I do not plan on abandoning this project as even though I have patched our original software, my plan is to use this library extensively in a new application eventually.  All this to say that I have limited time and resources to give my full attention to this package right now.  I will make my best attempt to patch the library to add the last bit of functionality in by tomorrow at 5pm (American CST).  Another thing to note is that the Readme is also missing some crucial information as I have just read through it again to see what I missed. I'll quickly outline them here so that if I cannot add the documentation by tomorrow you will know what features exist that have not been documented.

### Missing Documentation of key features:
* The logging system mentioned in the "Configuring the client" section of the documentation. This allows for toggling error messages and TCP I/O via console messages.  It is initialized in "lib/Connection.js" on lines 39-42, implemented in "lib/Log.js", and used throughout the library anywhere that a message needs to be logged. The message types need to be documented.
* The Event system.  The entire library is a class extension of the EventEmitter class, and this system is used internally to fulfill Promises due to the unordered nature of TCP requests, but it is also intended to be used by the end-user to listen for specific events that are triggered by activity within the phone system.  The names and payloads of these key events need to be documented.

Thanks for understanding why the library is incomplete.  If you have any additional concerns or requests feel free to submit a pull request at any time, and if you know that you will be using AND testing this library extensively, throw me your contact info if you'd like to become a collaborator on this project so you can push changes to github and npm during your testing.

**Comment by pwbrown** [comment]
@HGeertsma , I have updated the package to version 1.0.3 to address the issues you brought up, as well as to add the missing documentation I mentioned above.  I do not have the time right now to test the functionality extensively, but upon initial testing they appeared to construct the proper requests and function accordingly.  I'm going to close this issue for right now, but if find a blatant bug related to the new changes or in another area, please submit a pull request or open another issue, and I will try to address it as quickly as possible. Thank you!
